
#ifndef IFX_REG_H
#define IFX_REG_H
#include "_Cfg/IfxAsclin_reg.h"
#include "_Cfg/IfxBmu_reg.h"
#include "_Cfg/IfxCbs_reg.h"
#include "_Cfg/IfxCcu6_reg.h"
#include "_Cfg/IfxCpu_reg.h"
#include "_Cfg/IfxDma_reg.h"
#include "_Cfg/IfxDsadc_reg.h"
#include "_Cfg/IfxEbcu_reg.h"
#include "_Cfg/IfxEmem_reg.h"
#include "_Cfg/IfxEray_reg.h"
#include "_Cfg/IfxGlobal_reg.h"
#include "_Cfg/IfxGpt12_reg.h"
#include "_Cfg/IfxGtm_reg.h"
#include "_Cfg/IfxInt_reg.h"
#include "_Cfg/IfxLmu_reg.h"
#include "_Cfg/IfxMc_reg.h"
#include "_Cfg/IfxMcds_reg.h"
#include "_Cfg/IfxMchk_reg.h"
#include "_Cfg/IfxMsc_reg.h"
#include "_Cfg/IfxCan_reg.h"
#include "_Cfg/IfxOvc_reg.h"
#include "_Cfg/IfxFlash_reg.h"
#include "_Cfg/IfxPort_reg.h"
#include "_Cfg/IfxQspi_reg.h"
#include "_Cfg/IfxSbcu_reg.h"
#include "_Cfg/IfxScu_reg.h"
#include "_Cfg/IfxSdma_reg.h"
#include "_Cfg/IfxSent_reg.h"
#include "_Cfg/IfxSmu_reg.h"
#include "_Cfg/IfxSrc_reg.h"
#include "_Cfg/IfxStm_reg.h"
#include "_Cfg/IfxVadc_reg.h"
#include "_Cfg/IfxXbar_reg.h"

#endif /* IFX_REG_H */
