/* (c) 2000-2008 HighTec EDV-Systeme GmbH */
#ifndef _HAVE_TRICORE_TRANSMIT_BUFFER_SHARETYPES_H_
#define _HAVE_TRICORE_TRANSMIT_BUFFER_SHARETYPES_H_



#endif /* _HAVE_TRICORE_TRANSMIT_BUFFER_SHARETYPES_H_ */

